apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: influx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      volumes:
      - name: influx-volume
        persistentVolumeClaim:
          claimName: influx-volumeclaim
      - name: docker-data
        hostPath: 
          path: /var/run/docker.sock
      containers:
      - name: influx
        image: influx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influx-volume
          mountPath: /var/lib/influxdb
        - name: docker-data
          mountPath: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: influx
spec:
  type: ClusterIP
  selector:
    app: influx
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
