apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: influx
  hostPath:
    path: /var/lib/influxdb